import Head from "next/head";
import { Inter } from "@next/font/google";
import PostCard from "../components/PostCard";
import ToolTip from "../components/ToolTip";
import Link from "next/link";
import { useStore } from "../context";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [posts] = useStore()
  return (
    <>
      <Head>
        <title>Blog Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 z-50 backdrop-blur-md bg-white/30 flex justify-around shadow-md h-16 items-center">
        <h2 className="font-bold text-xl mb-2">Blog Post</h2>
        <form className="w-1/3">
          <input
            type="search"
            className="rounded-md bg-transparent w-full py-2 px-2 outline outline-gray-400 outline-1 focus:outline-blue-400"
          />
        </form>
        <div className="w-10 h-10">
          <ToolTip>
            <Link href={"/dashboard"}>
              <img
                src="https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg"
                alt="profile img"
                data-bs-toggle="tooltip"
                className="w-full h-full"
              />
            </Link>
          </ToolTip>
        </div>
      </header>
      <main className="mx-24">
        <div className="grid sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-4 my-8">
          {posts?.posts?.map((post) => (
            <PostCard post={post} key={post?.id} />
          ))}
        </div>
      </main>
    </>
  );
}
